from action import *
from attitude import *
from being import *
from place import *
from quality import *
from quantity import *
from relative import *
from state import *
from substance import *
from time import *